services:
  kounga_erp.api:
    image: ${DOCKER_REGISTRY-}koungaerpapi
    build:
      context: .
      dockerfile: kounga_erp.api/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest

  database:
    image: postgres

  pgadmin:
     image: dpage/pgadmin4:9.8

  mailpit:
    image: axllent/mailpit

volumes:
  postgresdb:
  sqlserverdata:  
  mailpitdata: