<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Templates\Emails\VerifyEmailAddressEmail.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\Emails\_EmailLayout.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Templates\Emails\VerifyEmailAddressEmail.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="RazorLight" Version="2.3.1" />
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\kounga_erp.api.Domain\kounga_erp.api.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTO\" />
  </ItemGroup>

</Project>
